#!/bin/bash
set -e

case "$1" in
    remove|purge)
        # Remove desktop entry
        rm -f /usr/share/applications/aurora-music.desktop
        
        # Update desktop database
        update-desktop-database /usr/share/applications || true
        ;;
    
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
